---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: admin
  namespace: default
  labels:
    paastel.io/api-user-credentials: "true"
  annotations:
    paastel.io/roles: "admin"
stringData:
  username: "admin@paastel.io"
  password: "my_super_hash"
