---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: admin
  namespace: default
  labels:
    paastel.io/api-user-credentials: "true"
  annotations:
    paastel.io/roles: "admin"
stringData:
  username: "admin@paastel.io"
  password: "$argon2id$v=19$m=19456,t=2,p=1$1SoziBLmGitKRfXC2+e7Ng$hfPRJDDkKyLH3FyHuqxm397sxPkmVkzydPI+LDQp+OU"
