name: github pages

on:
  push:
    branches:
      - main
    paths:
      - 'book/**'
  # pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.37'

      - name: Build mdBook
        run: |
          cd book/
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
